# Generated by Django 5.2 on 2026-06-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_team_auto_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='max_resubmissions',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
