# Generated by Django 5.2 on 2026-05-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_archive_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='phase2_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('active', 'Active'), ('needs_review', 'Needs Review'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='active', max_length=20),
        ),
    ]
