# Generated by Django 5.2 on 2026-05-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='can_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='expertise',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='max_teams',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.DeleteModel(
            name='SupervisorProfile',
        ),
    ]
