# Generated by Django 5.2 on 2026-05-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='max_teams',
        ),
        migrations.AddField(
            model_name='user',
            name='max_teams_review',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='user',
            name='max_teams_supervise',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
