# Generated by Django 5.2 on 2026-05-30 01:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_add_reviewer_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviewergrade',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reviewergrade',
            name='component',
            field=models.CharField(choices=[('single', 'Single'), ('report', 'Report'), ('presentation', 'Presentation')], default='single', max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='supervisor_presentation_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='supervisor_report_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='reviewergrade',
            unique_together={('submission', 'reviewer', 'component')},
        ),
    ]
