# Generated by Django 5.2 on 2026-05-30 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0005_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='guide_file',
            field=models.FileField(blank=True, null=True, upload_to='milestone_guides/'),
        ),
    ]
