# Generated by Django 5.2 on 2026-05-30 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_add_project_edit_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_links', to='projects.project')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
