# Generated by Django 5.2 on 2026-05-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('deadline', 'Deadline'), ('feedback', 'Feedback'), ('meeting', 'Meeting'), ('approval', 'Approval'), ('risk', 'Risk Alert'), ('invite', 'Team Invite'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
